trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'sBuild'
    displayName: 'Build'
    jobs:
      - template: pipelines/build.yml
        parameters:
          buildName: jBuild
          displayTitle: 'Build'
  - stage: 'sDeployDEV'
    displayName: 'Deploy DEV'
    jobs:
      - template: pipelines/docker.yml
        parameters:
          displayTitle: 'Push Docker Image on DEV'
          containerRegistry: 'pdasolucoes.azurecr.io'
          dockerImageName: 'pda-os-api-dev'