trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'sBuild'
    displayName: 'Build'
    jobs:
      - template: pipelines/build.yml
        parameters:
          buildName: jBuild
          displayTitle: 'Build'