trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'sBuild'
    displayName: 'Build'
    jobs:
      - template: pipelines/build.yml
        parameters:
          buildName: jBuild
          displayTitle: 'Build'
  - stage: 'sDeployDEV'
    displayName: 'Deploy DEV'
    jobs:
      - template: pipelines/docker.yml
        parameters:
          
          displayTitle: 'Push Docker Image on DEV'
          containerRegistry: 'pdasolucoes'
          dockerImageName: 'pda-os-api-dev'
      - template: pipelines/deploy.yml
        parameters:
          environmentName: 'DEVELOPMENT'
          displayTitle: 'Deploy API in Development'
          poolName: 'Azure Pipelines'
          azureSubscriptionName: 'cloud'
          containerRegistry: 'pdasolucoes'
          dockerImageName: 'pda-os-api-dev'
          dockerImageTag: latest
          webAppName: 'pda-os-api'
          webAppSlot: 'dev'